export const UNIT_PKG_LIST = [
    "BALES",
    "BOTTLECRATE",
    "BUNDLES",
    "BAG",
    "BUCKET",
    "BOTTLES",
    "BAR",
    "BOTTLE,BULBOUS",
    "BOX",
    "CAN",
    "CBM",
    "CHEST",
    "COFFIN",
    "COIL",
    "CONTAINER",
    "CRATES",
    "CASE",
    "CARTON",
    "DDDD",
    "DRUM",
    "EA",
    "FLEXIBAG",
    "FLEETS",
    "OTHERGT",
    "INGOTS",
    "METER",
    "NET",
    "PCS",
    "PLATE",
    "PIPE",
    "PKGS",
    "PALLET",
    "TRAYPACK",
    "REELS",
    "ROLL",
    "SKID",
    "STEEL DRUM",     // Extracted from screenshot 3
    "SET",            // Extracted from screenshot 4
    "SKELETON CASE",
    "TANK",
    "TON",
    "UNIT",
    "VAN",
    "BULK, GAS",
    "BULI ,LIQUID",
    "BULK,SOLID, LARGE,PARTICLE",
    "BULK,SOLID,GRANULAR",
    "BULK,FINE,PARTICLE",
    "W/BOXES",
    "WOODEN CASE",
    "WOODEN PALLET"
];


// Container size
export const CONTAINER_SIZE_LIST = [
    "20 HC",
    "20 GP",
    "20 DG",
    "20 HQ",
    "20 DC",
    "20 DR",
    "20 OT",
    "20 FR",
    "20 RF",
    "20 TK",

    "40 HC",
    "40 DR",
    "40 SR",
    "40 GP",
    "40 DG",
    "40 HQ",
    "40 DC",
    "40 OT",
    "40 FR",
    "40 RF",
    "40 TK",

    "45 HC",
    "45 DC",

    "48 HC",
    "58 DC",

    "BULK"
];
